### ISSUE TITLE
may i use this game on WeChat?

### ISSUE THREAD

**Issue by funnyndk** [LastLeaf/ludum-dare-42#1]

**Comment by funnyndk** [comment]
holle , LastLeaf.
im really a fan of this game, like it a lot. Now im thinking about change/put it on wechat minigame to let more people try it. May i use this code to my wechat?

**Comment by LastLeaf** [comment]
Sure! Feel free to use the code under CreativeCommons and MIT.

I tried to put it on wechat minigame last year, but finally gave up because I was too busy (I am a member of [wechat-miniprogram](https://github.com/wechat-miniprogram).

I can also provide some help in my spare time if you are interested in porting it or developing further!
